version: 2
jobs:
  build_server:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: mkdir -p workspace
      - run:
          name: Build binary
          command: go build -o workspace/armeria cmd/armeria/main.go
      - run:
          name: Run unit tests
          command: go test -race ./...
      - persist_to_workspace:
          root: workspace
          paths:
            - armeria
  build_client:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Build client
          command: yarn build
  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Copy binary to server
          command: |
            scp -o StrictHostKeyChecking=no workspace/armeria root@armeria.mdr.dev:/opt/armeria/armeria-$CIRCLE_BUILD_NUM
      - run:
          name: Symlink to the new binary
          command: |
            ssh -o StrictHostKeyChecking=no root@armeria.mdr.dev ln -s -f /opt/armeria/armeria-$CIRCLE_BUILD_NUM /opt/armeria/armeria
      - run:
          name: Restart armeria
          command: |
            ssh -o StrictHostKeyChecking=no root@armeria.mdr.dev systemctl restart armeria
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_server
      - build_client
      - deploy:
          requires:
            - build_server
            - build_client
          filters:
            branches:
              only: master