version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: mkdir -p workspace
      - run:
          name: Build binary
          command: go build -o workspace/armeria cmd/armeria/main.go
      - run:
          name: Run unit tests
          command: go test -race ./...
      - persist_to_workspace:
          root: workspace
          paths:
            - armeria
  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
      - attach_workspace:
          at: workspace
      - run: scp -o StrictHostKeyChecking=no workspace/armeria root@armeria.mdr.dev:/opt/armeria/armeria-$CIRCLE_BUILD_NUM
      - run: ssh -o StrictHostKeyChecking=no root@armeria.mdr.dev "systemctl restart armeria

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test