version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Build binary
          command: go build -o armeria cmd/armeria/main.go
      - run:
          name: Run unit tests
          command: go test -race ./...
  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
        - run: curl -XPOST https://armeria.mdr.dev/api/reload?key=$RELOAD_KEY
        - run: scp -o StrictHostKeyChecking=no ./armeria root@armeria.mdr.dev:/opt/armeria/armeria
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test