version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: run unit tests
          command: go test -race ./...
      - run:
          name: build binary
          command: go build cmd/armeria/main.go