version: 2
jobs:
  test_and_build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: run unit tests
          command: go test -race ./...
      - run:
          name: build binary
          command: go build -o armeria cmd/armeria/main.go
  deploy:
    docker:
      - image: circleci/golang:1.12
    steps:
        - run: curl http://something.com/a/b